development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://ecidxmrndmspnc:2ff13e63b3063ae05b839a673df1714f3fc6a30e9b30146d9ff3194f224484b9@ec2-54-225-121-235.compute-1.amazonaws.com:5432/d7nc7dml3j02g
  channel_prefix: ecomapp_production
